name: Deploy

concurrency:
  group: deploy-${{ github.repository }}
  cancel-in-progress: false

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  ORG: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  CONT_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set organization name to lowercase
        run: |
          echo "ORG_LC=${ORG,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL=__VITE_API_BASE_URL__ \
            --build-arg VITE_PUBLIC_POSTHOG_KEY=__VITE_PUBLIC_POSTHOG_KEY__ \
            --build-arg VITE_PUBLIC_POSTHOG_HOST=__VITE_PUBLIC_POSTHOG_HOST__ \
            --build-arg VITE_GA_ID=__VITE_GA_ID__ \
            --build-arg VITE_CLARITY_ID=__VITE_CLARITY_ID__ \
            -t $REGISTRY/$ORG/$IMAGE_NAME:latest \
            -t $REGISTRY/$ORG/$IMAGE_NAME:$(date +%Y%m%d%H%M%S) \
            .
          docker push $REGISTRY/$ORG_LC/$IMAGE_NAME --all-tags

  deploy:
    needs: build-and-push
    runs-on: ['self-hosted', 'frontend']
    env:
      TZ: Asia/Seoul
    steps:
      - name: Set organization name to lowercase
        run: |
          echo "ORG_LC=${ORG,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Getting current image name
        id: current_img
        run: |
          CURRENT_IMG=$(docker inspect $CONT_NAME --format='{{.Config.Image}}' 2>/dev/null || echo "")
          echo "image=$CURRENT_IMG" >> $GITHUB_OUTPUT

      - name: Pulling latest image
        run: docker pull $REGISTRY/$ORG_LC/$IMAGE_NAME:latest

      - name: Executing container using Docker Compose
        run: |
          docker compose \
          -f ${{ secrets.FESTIVAL_DOCKER_COMPOSE_FILE_PATH }} \
          --env-file ${{ secrets.FESTIVAL_ENV_PATH }} \
          up -d --no-build --pull never \
          $CONT_NAME

      - name: Flushing docker cache
        run: docker buildx prune -f
